### ISSUE TITLE
User-Menu

### ISSUE THREAD

**Issue by momoKitsune** [FHTW-HWSE/projekt-group12-project1#4]
Ein User Interface:
Einen Raum erstellen
- Reihen und Spalten

Einen Raum belegen
- StudentID anlegen
- StudentID speichern

Eintragen eines Infizierten
-StudentID auswählen

Einen Raum abfragen
- direkten Nachbarn
- indirekten Nachbarn

Zurück und Beenden.

**Comment by RefRexi** [comment]
fixed
